events {}

http {
    log_format sigma_probe_json escape=json
        '{"time_iso8601":"$time_iso8601",'
        '"remote_addr":"$remote_addr",'
        '"request_method":"$request_method",'
        '"request_uri":"$request_uri",'
        '"status":"$status",'
        '"body_bytes_sent":"$body_bytes_sent",'
        '"http_user_agent":"$http_user_agent",'
        '"host":"$server_name"}';

    upstream app_backend { server app:3000; }
    server {
        listen 80;
        server_name lab.local;
        access_log /logs/access.log sigma_probe_json;
        location / {
            proxy_set_header Host $host;
            proxy_pass http://app_backend;
        }
    }
}
